### ISSUE TITLE
マルチサイクルのサポート

### ISSUE THREAD

**Issue by Aono082** [ehimetakahashilab/Hybrid-TPI#15]
## WHY
2019 デザインガイア論文の実験データで必要なため

## WHAT
- BbCcおよびcopの可制御性を指定のサイクル数分だけ保持できるようにする
- FFにメトリクスを保持できるようにする
- BbCc計算をサイクルをまたいで計算できるようにする

**Comment by MaineK00n** [comment]
リポジトリ分割によりclose
