### ISSUE TITLE
TPI選択手法を実装

### ISSUE THREAD

**Issue by MaineK00n** [ehimetakahashilab/Hybrid-TPI#32]
## WHY
- Hybrid TPIで使用されているTPI選択手法が求められる

### deprecated
- ~Hybrid TPI論文で引用されているTPI選択手法を実装する~
~[Embedded.Deterministic.Test.Points.pdf](https://github.com/ehimetakahashilab/Hybrid-TPI/files/3761591/Embedded.Deterministic.Test.Points.pdf)~

![66800958-44ac2580-ef52-11e9-87a0-06fbc2c0275f](https://user-images.githubusercontent.com/16035056/67381192-7f533500-f5c6-11e9-94ad-d78eb0f71f2f.png)

## current
1)cC計算
2)cCを参照して一番大きい値を持つゲートを1個選択(cなら０、Cなら１をセット)
3）前の値と新しい値が異なる限り、後方に移動してbとBを再計算します。同時に、訪問したすべてのネットで競合ｃおよびCを更新します。 #38 
4）前の値と新しい確率の差が特定のしきい値より小さくなるまで、信号確率が再計算されます。競合ｃおよびCも更新されます。 #37 
5) 1,2,3,4をTPI数分繰り返す。

## REF
#14 (3)~5))

**Comment by MaineK00n** [comment]
#14 pending

**Comment by Aono082** [comment]
TPの出力はTPを選んだ順番に出してほしい

**Comment by Aono082** [comment]
これも本当はreference作って検証せんといかん気がする
面倒くさすぎて手が動かない
