### ISSUE TITLE
実装とExcelの変数への理解を統一

### ISSUE THREAD

**Issue by MaineK00n** [ehimetakahashilab/Hybrid-TPI#33]
## WHY
- 実装とExcelで変数の理解が異なり、結果が異なっている

## WHAT
- 実装側には正しいb/Bを示すコメントを書く
- Excel側には正しいb_0/b_1を示すコメントを書く
- 格納先や計算結果が異なる場合は修正する

**Comment by Aono082** [comment]
[s27_reference_multi.xlsx](https://github.com/ehimetakahashilab/Hybrid-TPI/files/3761858/s27_reference_multi.xlsx)
