### ISSUE TITLE
各メトリクス計算の厳格化

### ISSUE THREAD

**Issue by MaineK00n** [ehimetakahashilab/Hybrid-TPI#49]
## WHY
- 計算を厳格にしたい

## WHAT
- [ ] tpiのcopを0/1にセット
- [x] tpiセット時のルート計算を片方に
- [x] bBcCメトリクス再計算の見直し
- [ ] tpiに選択されたbBcCメトリクスの扱い
- [x] tpiにsetする値の修正

**Comment by Aono082** [comment]
>tpiセット時のルート計算を片方に

これはどういう意味？

**Comment by MaineK00n** [comment]
値が固定されるので，ルート探索は0/1の場合ではなく，tpi_valueの場合だけでよい
fieldは2つ0/1の場合あるので，tpi_valueの場合を求めて，fieldにコピーすることによって，ルート探索の計算量を下げる

**Comment by Aono082** [comment]
TPによってbBルートに影響があるのは01の片方だけってことか
なるほど
どっちに影響があるのか調べるのは難しそう

**Comment by MaineK00n** [comment]
> copを0/1にセット
これによってはcop=0になると無限大になるが，これによって，cCメトリクスに影響が大きく，選択されるTPに影響が大きい

> TPによってbBルートに影響があるのは01の片方だけってことか
なるほど
どっちに影響があるのか調べるのは難しそう

そんなに難しい話ではなく，
https://github.com/ehimetakahashilab/Hybrid-TPI/blob/0ff9dfe24a64b3c362e3b1bcaa302fb5e972953e/src/calc_cCbB.c#L40
では，0/1両方に対して，計算しているので，
tpi_valueの場合だけで良い気がした

**Comment by MaineK00n** [comment]
勘違いしているかもしれない

**Comment by MaineK00n** [comment]
TPにセットされたcopを厳密に0/1にセットするなら，ルートが0/1の片方のみになるはずなので，bBcCのどちらを0にすべきと考える
